//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
       __o = Html.ActionLink("Form Builder", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 5 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 6 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 7 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 8 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 9 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
       __o = Html.ActionLink("Form Builder", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 5 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 6 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 7 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 8 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 9 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Shared\_Layout.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
