//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__SignUp_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__SignUp_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
using (Html.BeginForm("Index", "Home", new{id="signupform"}))
{


#line default
#line hidden

#line 3 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 4 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
                        



#line default
#line hidden

#line 5 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
                                                     


#line default
#line hidden

#line 6 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
                                                        


#line default
#line hidden

#line 7 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
                                                                    



#line default
#line hidden

#line 8 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
__o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 9 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
   __o = Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 10 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 11 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" });


#line default
#line hidden

#line 12 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
   __o = Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 13 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @id="Password",} });


#line default
#line hidden

#line 14 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
   __o = Html.Label("Confirm Password", htmlAttributes: new { @class = "control-label col-md-2" })Html.ValidationMessageFor(model => model.Password, "", new { @clss = "text-danger" });


#line default
#line hidden

#line 15 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C       B38379C3093EditorFor1modelF=> model.ormBuildr_new { V1\FormBuilderV= 1\Views\Home\_Siform-gnUp.cs", @id="ConfirmPassword",
@name="confirm }Html.Label("Confirm Password", htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 16 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C
#line hidden

#line 17 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96CF63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
      
}

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__SignUp_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__SignUp_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
__o = ;


#line default
#line hidden

#line 2 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"


#line default
#line hidden

#line 3 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
__o = ;


#line default
#line hidden

#line 4 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
                        

#line default
#line hidden

#line 5 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
__o = ;


#line default
#line hidden

#line 6 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
   __o = ;


#line default
#line hidden

#line 7 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = ;


#line default
#line hidden

#line 8 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = ;


#line default
#line hidden

#line 9 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
   __o = ;


#line default
#line hidden

#line 10 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = ;


#line default
#line hidden

#line 11 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = ;


#line default
#line hidden

#line 12 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
      

#line default
#line hidden
}
}
}
9C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 11 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" });


#line default
#line hidden

#line 12 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
      
}

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__SignUp_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__SignUp_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
__o = ;


#line default
#line hidden

#line 2 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"


#line default
#line hidden

#line 3 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
__o = ;


#line default
#line hidden

#line 4 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
                        

#line default
#line hidden

#line 5 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
__o = ;


#line default
#line hidden

#line 6 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
   __o = ;


#line default
#line hidden

#line 7 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = ;


#line default
#line hidden

#line 8 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = ;


#line default
#line hidden

#line 9 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
   __o = ;


#line default
#line hidden

#line 10 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = ;


#line default
#line hidden

#line 11 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
       __o = 


#line default
#line hidden

#line 12 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\_SignUp.cshtml"
      

#line default
#line hidden
}
}
}
