//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Index";


#line default
#line hidden

#line 3 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Html.ActionLink("Create Account", "SignUp", "Home", new { Id = "signuplink" });


#line default
#line hidden

#line 4 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Html.ActionLink("Sign In", "Index", "Home", new { Id = "signinlink" });


#line default
#line hidden
DefineSection("Scripts", () => {


#lline hidden
ne 5 "C:\Users\Invia-ILC\AppDat5\Local\Temp\6F63FB6C96C14AB38379C3093B6A751F568D\8\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Index";


#line default
#line hidden

#line 3 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Html.ActionLink("Create Account", "SignUp", "Home", new { Id = "signuplink" });


#line default
#line hidden

#line 4 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Html.ActionLink("Sign In", "Index", "Home", new { Id = "signinlink" });


#line default
#line hidden
DefineSection("Scripts", () => {


#line 5 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\6\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Index";


#line default
#line hidden

#line 3 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Html.ActionLink("Create Account", "SignUp", "Home", new { Id = "signuplink" });


#line default
#line hidden

#line 4 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Html.ActionLink("Sign In", "Index", "Home", new { Id = "signinlink" });


#line default
#line hidden
DefineSection("Scripts", () => {


#line 5 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\4\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Index";


#line default
#line hidden

#line 3 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Html.ActionLink("Create Account", "SignUp", "Home", new { Id = "signuplink" });


#line default
#line hidden

#line 4 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Html.ActionLink("Sign In", "Index", "Home", new { Id = "signinlink" });


#line default
#line hidden
DefineSection("Scripts", () => {


#li
#line 5 "C:\Users\Invia-ILC\AppData\Local\Temp\5F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
      __o = isCreated;


#line default
#line hidden
ne 5 "C:\Users\Invia-ILC\AppData\Local\Temp\6F63FB6C96C14AB38379C3093B6A751F568D\2\FormBuilder_V1\FormBuilder_V1\Views\Home\Index.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
